function(enable_ipo)
    if(ENABLE_IPO)
        include(CheckIPOSupported)
        check_ipo_supported(RESULT result OUTPUT output)
        if(result)
            set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON PARENT_SCOPE)
        else()
            message(SEND_ERROR "IPO is not supported: ${output}")
        endif()
    endif()
endfunction()
