# C++ standard — override at configure time: cmake -DCXX_STANDARD=23 ..
if(NOT DEFINED CXX_STANDARD)
    set(CXX_STANDARD 20)
endif()
set(CMAKE_CXX_STANDARD ${CXX_STANDARD} CACHE STRING "C++ standard to use")
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set_property(CACHE CMAKE_CXX_STANDARD PROPERTY STRINGS 17 20 23 26)
