SET(PROJECT_NAME myproject)
SET(VERSION 0.0.1)

# C++ standard — override at configure time with -DCXX_STANDARD=23 etc.
IF(NOT DEFINED CXX_STANDARD)
    SET(CXX_STANDARD 20)
ENDIF()
SET(CMAKE_CXX_STANDARD ${CXX_STANDARD} CACHE STRING "C++ standard to use" FORCE)
SET_PROPERTY(CACHE CMAKE_CXX_STANDARD PROPERTY STRINGS 17 20 23 26)